[http]
enabled = true
hostname = 0.0.0.0
port = 6680

[audio]
mixer = alsamixer
output = alsasink device=hw:3,0

[alsamixer]
enabled = true
card = 3
control = PCM
min_volume = 0
max_volume = 100
volume_scale = cubic

[tunein]
enabled = true
timeout = 5000