[audio]
mixer = alsamixer
output = alsasink device=hw:0,0

[alsamixer]
enabled = true
card = 0
control = PCM
min_volume = 0
max_volume = 100
volume_scale = cubic

[http]
enabled = true
hostname = 0.0.0.0
port = 6680

[stream]
enabled = true
protocols =
    https
timeout = 5000

[tunein]
enabled = true
timeout = 5000